### ISSUE TITLE
Integrate watcher into CI for WH

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent-metal/tt-metal#4136]
All tests fail with one of these two signatures, with the 16,02, or 00,48 core co-ordinates:

On core (x=1,y=1): noc1:ncrisc{(16,02) 0x00000020, 2048}
On core (x=1,y=1): noc0:brisc{(00,48) 0x000005a0, 2048}

- [x] #4083
- [x] #4101
- [x] #4102
- [x] #4105
- [x] #4106
- [x] #4107
- [x] #4108
- [x] #4111
- [x] #4112
- [x] #4114
- [x] #4115
- [x] #4116
- [x] #4117
- [x] #4118

**Comment by tt-aho** [comment]
The problem for this error, `On core (x=1,y=1): noc0:brisc{(00,48) 0x000005a0, 2048}`, is that when extracting the noc_x and noc_y for watcher verification, there are extra bit shifts.

When we generate the xy values in `genfiles.cpp`, we bit shift the xy values by 4 for WH already (noc_addr_local_bits is 36)

![image](https://github.com/tenstorrent-metal/tt-metal/assets/109362939/425218b5-6ff5-44c5-b80b-a5f1d2035dc9)

To create the address for watcher sanitization, we use NOC_XY_ADDR2, which shifts the xy passed in by 36 which means that xy now starts at bit 40 since the xy value is already shifted by 4.
![image](https://github.com/tenstorrent-metal/tt-metal/assets/109362939/95697aba-8456-4b57-8d05-51b831945f21)

The correct dram noc is (0, 11), where 11 is 0b001011, but when watcher is validating it is reading it shifted by 4 as 0b110000 which is 48. This should only affect watcher validation so the actual reads should be correct.

**Comment by pgkeller** [comment]
Assign myself to fix the watcher double shift on WH

**Comment by pgkeller** [comment]
Watcher issue has been fixed, should retest the list above, likely good to go

**Comment by TT-billteng** [comment]
thanks @pgkeller I've kicked off a stress test run on main with your fix

**Comment by TT-billteng** [comment]
All green now on main https://github.com/tenstorrent-metal/tt-metal/actions/runs/7441497962
