### ISSUE TITLE
ttl.tensor.move causes PCC mismatches or hangs when called multiple times back to back

### ISSUE THREAD

**Issue by arakhmati** [tenstorrent-metal/tt-metal#4171]

**Comment by arakhmati** [comment]
To reproduce:
- `git checkout arakhmati/ttnn-reallocate-mismatch`
- `pytest tests/ttnn/unit_tests/test_reallocate.py`

**Comment by abhullar-tt** [comment]
Issue was due to input to move being deallocated twice

**Comment by tt-aho** [comment]
This was a problem we noted in Resnet as well when adding sharded move. The problem is that to deallocate a buffer, the allocator only uses the buffer's address to find the block to deallocate.

So when the output tensor of move is at the exact same address as the input tensor, when the input tensor's buffer is deallocated either explicitly or when the tensor is destructed, the output tensor's buffer will be deallocated since they are the same address.

For sharded move we assert out for this case but a potential non-ideal workaround that was discussed is to deallocate the input and output tensor, then reallocate the output tensor again like below. This way input tensor's reference to the buffer/address is fully removed.

```
    // A tensor moved within L1 it is meant to reallocate at higher addresses and a tensor moved within DRAM is meant to reallocate at lower addresses
    // If the tensor is not allocated in a new address, there is no need to move the data
    if (move_within_same_mem_space and input_address == output_tensor.buffer()->address()) {
        auto device = input_tensor.device();
        input_tensor.deallocate();
        output_tensor.deallocate();
        output_tensor = create_device_tensor(input_tensor.shape(), input_tensor.dtype(), input_tensor.layout(), device, output_mem_config);
        return output_tensor;
    }
```

Otherwise a potentially more ideal solution is that to actually call `input_tensor.deallocate()` instead of `DeallocateBuffer(*input_tensor.buffer());` when we initially deallocate the input buffer so that we have space to allocate the output. We only keep the buffer around to pass around the buffer object's properties, but we can extract and pass them individually instead to the op. This will prevent the output being deallocated when the input in deallocated/destructed.

**Comment by abhullar-tt** [comment]
> auto device = input_tensor.device();

yeah on branch I kept the `DeallocateBuffer` and removed the `tensor.deallocate` call. I will swap the two and pull out the buffer object attributes. 

Fixing this bug exposed as issue with Bloom. it is hitting OOM because the input and output tensors get allocated at the same address. This means the move op would be noop (no better place to allocate its mem)

**Comment by tt-aho** [comment]
Maybe a more simple solution is that since we zero the buffer size in buffer deallocate, to just add this to the check for if we actually proceed to call the allocator's deallocate? This way the subsequent calls to input tensor's deallocate doesn't actually affect the allocator/output tensor?

```
   void Buffer::deallocate() {
    if (this->device_ == nullptr or not this->device_->initialized_ or this->size_ == 0) {
        return;
    }
    this->size_ = 0;
    TT_ASSERT(this->device_->allocator_ != nullptr, "Expected allocator to be initialized!");
    allocator::deallocate_buffer(*this->device_->allocator_, this->address_, this->buffer_type_);
}
```

**Comment by abhullar-tt** [comment]
> Maybe a more simple solution is that since we zero the buffer size in buffer deallocate, to just add a zero size check to the check for if we actually proceed to call the allocator's deallocate? This way the subsequent calls to input tensor's deallocate doesn't actually affect the allocator/output tensor?

yeah we could do this but I think its awkward in move op to be calling deallocate twice. I also think the case where input and output get allocated at the same address should be an error. In this case move fails to do what we want because it never got reallocated at a higher / lower address and there needs to be another method to get more space

**Comment by jliangTT** [comment]
Hey @arakhmati and @abhullar-tt , promoting this to p0 to make sure this gets worked on with top priority c.c. @jvasilje

**Comment by abhullar-tt** [comment]
> Hey @arakhmati and @abhullar-tt , promoting this to p0 to make sure this gets worked on with top priority c.c. @jvasilje

PR https://github.com/tenstorrent-metal/tt-metal/pull/4517 addresses this bug

**Comment by arakhmati** [comment]
> > Hey @arakhmati and @abhullar-tt , promoting this to p0 to make sure this gets worked on with top priority c.c. @jvasilje
> 
> PR #4517 addresses this bug

I updated bloom to use L1 Memory Config for most ops on the branch of this PR.

I still had to put a few ops into DRAM to get a numerical match but it seems like a different issue.

We should be able to close this issue tomorrow and then we can use Issue #4489  for tracking the remaining numerical mismatches in bloom

**Comment by arakhmati** [comment]
The PR has been merged to main. Closing this issue
