### ISSUE TITLE
AllGather Optimizations

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent-metal/tt-metal#5167]
- [x] Multi-link all gather
- [x] Double buffering (on branch)
- [ ] Use both nocs on eth core for noc transactions (reading for sender core, writing for receiver core?)
- [ ] Add sharding support for better access patterns
- [x] Offload some noc transactions to worker cores
- [ ] Bi-Directional support

Lower priority:
- [x] Remove header from all gather transfers. This might make the receiver kernel more complicated/may not be worth it?

**Comment by SeanNijjar** [comment]
Tagging along for this. Working on some lower level optimizations that will plug into the existing implementation(s).
The brief so far:

## Adding Microbenchmarks
- [x] Add concept of eth transaction channels to enable eth sends to be in flight while erisc checks for acks from receiver independently (without a hard sync/block).
  - Hits in the range of 10-10.5GBps throughput with 50KiB buffers, which is ~85% of theoretical peak and about 90% of realized peak (using the stream hardware). 
    - I think this is probably pretty close to as good as we'll get on erisc. We can of course play around with the instruction sequence to extract a couple more %, but largely, I don't think we're hitting 11.5GBps with erisc and without streams.
  - 7-10GBps with 32KiB buffers (depending on how many parallel transaction channels we enable
  - A more concrete table will come later with the PR for this microbenchmark

  - [x] Incorporate into all gather as prototype:
    - only 5-15% bump in all-gather device throughput over most recent best
      - largely perf limited here by current implementation which essentially serializing noc reads with eth sends, which is not good for performance

- [ ] Develop new microbench mark and erisc kernel scheme which lets us fully decouple noc reads from eth sends
   - noc reads and eth sends will only ever block one another due to backpressure (likely from eth link)
     - as opposed to noc read blocking eth send or vice versa due to how the kernel is implemented   
  - [ ] Integrate with all-gather kernel (double buffering)
  - [ ] Integrate with all-gather kernel (triple buffering)
  - [ ]  (maybe) Integrate with all-gather kernel (quad buffering) if it simplifies implementation of triple buffering

**Comment by SeanNijjar** [comment]
Added erisc data mover master issue here: #5549 

Includes bidirectional support mentioned above.

**Comment by SeanNijjar** [comment]
On my TODO list: break this into sub-tasks with the appropriate priorities.

**Comment by SeanNijjar** [comment]
I'm going to close this issue. We have other standalone issues tracking some of these and others are completed:

> Use both nocs on eth core for noc transactions (reading for sender core, writing for receiver core?)

We don't have any real data that this is a limiter so I don't think it's worthy of opening this as a dedicated issue 

> Bi-Directional support

About to merge but is also tracked in #6040 

> Add sharding support for better access patterns

In progress and tracked by #6041
