### ISSUE TITLE
tt_py_untilize_with_halo.py:148 -- remove the assertion (shouldn't be there)

### ISSUE THREAD

**Issue by shwetankTT** [tenstorrent-metal/tt-metal#5204]
This assertion should not be there.
Shapes which were Failing  due to this assertion

![image](https://github.com/tenstorrent-metal/tt-metal/assets/156869929/15f8500d-663b-4f53-a54d-91af55a174fd)

**Comment by mywoodstock** [comment]
@shwetankTT what is the status of each of these shapes' tests after removing the extraneous assertion?

**Comment by shwetankTT** [comment]
These tests are passing now.

**Comment by Adraca** [comment]
Interesting that the curve isn't monotonic because `softmax_large_tensor.cpp` already folds partial sums over ~80-tile passes above w=8192 — that's already a form of chunked/hierarchical accumulation, just not applied below w=8192 where `softmax.cpp` folds all `Wt` tiles into one running accumulator in a single pass.

Was a chunked variant of the small-kernel path considered as an alternative to `fp32_dest_acc_en=true`? PR #50624 (Equal-Count Welford) took a similar approach for variance — 32-partial leaves combined hierarchically instead of one wide accumulation — specifically to avoid losing precision without paying for a wider accumulator across the board. Curious whether the same
shape of fix was evaluated here and ruled out for a reason that isn't obvious from the issue, or if it just hasn't been tried yet.
