### ISSUE TITLE
Resnet50 e2e WH no-skips

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent-metal/tt-metal#5586]
Run resnet50 e2e on WH

**Comment by tapspatel** [comment]
Initial repro commands from working GS resnet50

```
git checkout shwetankTT/resnet
pytest -ssv /proj_sw/user_dev/tpatel/tt-metal-workspace/tt-metal-gs/tt-metal/tests/ttnn/integration_tests/resnet/resnet50.py::test_resnet
```

**Comment by tapspatel** [comment]
First failure occurs on shallow convs in `tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_composite_conv.py:245`

```
if padded_input_channels == 16 and (act_block_h_ntiles // out_subblock_h_ntiles % 2 != 0):
            assert is_1d_systolic
            # TODO: fix this temporary hack for shallow conv
>           assert act_block_h_ntiles % 2 == 0
E           AssertionError
```

Disabling this optimization for now

**Comment by tapspatel** [comment]
Next error: no L1 bank exists for core (x=8, y=0)

```
reader_indices_sharded_tensor = reader_indices_tt_tensor.to(self.device, mem_config)
E           RuntimeError: TT_THROW @ tt_metal/impl/allocator/allocator.cpp:235: tt::exception
E           info:
E           No L1 bank exists for core {}
E           (x=8,y=0)
```

**Comment by nsmithtt** [comment]
Thanks Taps! Can you file issues for these, tag them w/ Resnet50, op_cat: sliding window, CNNs and assign to me

**Comment by nsmithtt** [comment]
Actually, first do a bit of investigation on the second one, double check there isn't a shard spec override that using WH grid OOB

**Comment by tapspatel** [comment]
def determine_parallel_config(swo_params: SlidingWindowOpParams):

This function in file `tt_eager/tt_dnn/op_library/sliding_window_op_infra/tt_py_max_pool.py` has hardcoded values for GS. It needs to be changed for wormhole grid size (8x8 for n150 and 7x8 for n300). That is the cause of the above error where it's setting the wrong grid size and tries accessing a core that is not Tensix (so doesn't have an L1)

**Comment by tapspatel** [comment]
I selected a grid size of (8,8). Num of worker cores changed from 98 to using full 64 since 50176 / 64 = 784 (clean whole number). 25088 was determined based on input tensor size. [N, C, H, W] for input is [1, 3, 224, 224]. Convert this to [1, 1, NHW, C] is [1, 1, 1 * 224 * 224, 3] = [1, 1, 50176, 3]. This passed the l1 bank exists stage.

**Comment by tapspatel** [comment]
This function `uint32_t get_num_cores(CoreCoord grid_size, uint32_t out_nhw, uint32_t nbatch) {` in `tt_eager/tt_dnn/op_library/pool/max_pool_multi_core.cpp` needs to be updated with to account for WH grid sizes. It gets called in this line `uint32_t ncores = max_pool_helpers::get_num_cores(input.device()->compute_with_storage_grid_size(), out_nhw, nbatch);` when trying to create output tensors in `tt_eager/tt_dnn/op_library/pool/max_pool.cpp`. It returns a value of 98 which is incorrect and leads to assertion error down the read in this function `num_cores_to_corerange_set` because it tries setting output tensor core size to 98 but total core count is only 64.

Hardcoding this to 64 passes

**Comment by tapspatel** [comment]
After making these changes, resnet50 runs end to end on WH.

**Comment by mywoodstock** [comment]
How's the perf looking?

**Comment by davorchap** [comment]
This can be in CI on N150s (8x8) ?

**Comment by tapspatel** [comment]
performance: 59fps
Working on getting this into WH CI after refactoring and some cleanups

**Comment by mywoodstock** [comment]
Updating here too, we are now at `625`fps

**Comment by tapspatel** [comment]
Closing issue as test on WH has been merged in

**Comment by tapspatel** [comment]
Reopening as there are still certain features to enable (eg bfp8_b)

**Comment by nsmithtt** [comment]
Task is done, follow on work tracked via CNNs on Metal project
