### ISSUE TITLE
Falcon40B on 4/8 chips: resharding causing PCC drops

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#5771]
Reproducible on 4 chips as well without FD1.3 and tunneling

**Comment by tarafdarTT** [comment]
@aliuTT , could you put the shard specs of the input and output shards here. I can try to reproduce this even on a single chip.

**Comment by aliuTT** [comment]
seeing this on 8 chips as well

**Comment by aliuTT** [comment]
@tarafdarTT , can we revert this on main? We can sync offline about what we're seeing, but essentially FD1.3, BidirTunnelling and Falcon40B multichip PR changes are blocked, since on all our branches we have to revert locally to get all unit tests working.

**Comment by tarafdarTT** [comment]
@aliuTT 

hmm ultimately if that's the case I think we would be putting potentially buggy code back into main because the changes in the buffer mappings , (maps the host side tensor to a shard page) is incorrect but was previously not caught because we didn't have tests for certain shapes that I added with Reshard. 

If we do revert, can you see if you can add into CI a single chip version that still shows the bug. or point me to how to do that such that when I add this back I can compare against something. 

Without the unit test exposing this then when I add this back it will just end up breaking this again. 

Anyway feel free to revert, but ya we should sync on how to get a test into CI that exposes the bug that came with the Reshard PR, (my gut feeling is that it exposes an underlying bug that's already there, but without an isolating test its hard to say). 

CC: @davorchap , TLDR. with my Reshard changes I added changes that modified the mappings of host page to dev pages, these modifications should have been fixes to shapes that were previously untested but were tested more thoroughly in my reshard unit tests. However this PR has caused a PCC drop for falcon tests which from what I gather so far only show up in multi-chip tests. Hence we didn't have anything in CI to block any merges of this. For now we will revert this PR, and hopefully we can get a single-chip version of a test that can help me block this PR in the future if it remains buggy.

**Comment by TT-BrianLiu** [comment]
Fix is here: https://github.com/tenstorrent-metal/tt-metal/pull/5926.
Issue was caused by uneven shards per core. Last core has a few less pages, so we had uninitialized values in a vector of indices that fast dispatch was consuming and writing data to. 

@DrJessop FYI, fast dispatch assumes all shards are same per core right? I think we should have support for uneven shards. Naif filed a separate issue for this here: #5925.

**Comment by tarafdarTT** [comment]
I thought I added it but I think I must have messed up. I can look into
this.

**Comment by TT-BrianLiu** [comment]
"Passing" pipelines: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8161162949/job/22309334671

**Comment by TT-BrianLiu** [comment]
Uneven shards is better handled now and should not be corrupting tensors anymore. There are workarounds for tests like `untilize_with_halo` which still expects padded shard on last core.
