### ISSUE TITLE
python crash with garbage collector

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent-metal/tt-metal#5788]
a bug that @tt-nshanker is running into on stable diffusion unit test when trying to put group norm op on device. 
Needs immediate help. :-) 

@tt-nshanker please add instructions on how to reproduce. branch, test, command.

**Comment by tt-nshanker** [comment]
I was able to create a small unit test to reproduce the crash -
Branch name: `nshanker/group_norm_on_device_crash`
Test command - `pytest tests/ttnn/integration_tests/stable_diffusion/test_resnet_block_2d.py -k "512x512"`
The first time this test is run, it will load up the whole unet model which takes 20 seconds and it will cache on disk. After the first run, please set `load_from_disk =True` in  `tests/ttnn/integration_tests/stable_diffusion/test_resnet_block_2d.py` so that the model can be loaded from disk quickly in subsequent runs. The python crash occurs after 4 seconds. Last thing that is printed to screen is - `Done group norm. Convert to tile layout.`

**Comment by eyonland** [comment]
Is this a debug/assert/release build?
