### ISSUE TITLE
Support program cache on multi-device

### ISSUE THREAD

**Issue by s-jovic** [tenstorrent-metal/tt-metal#6031]
Currently, [test_falcon_model.py](https://github.com/tenstorrent-metal/tt-metal/blob/main/models/demos/falcon40b/tests/test_falcon_model.py) gives bad PCC.

Removing `use_program_cache` bumps PCC from 0.88 to 0.964 for the final output and improves the K and V on each layer.

cc @TT-BrianLiu @johanna-rock-tt

**Comment by TT-BrianLiu** [comment]
Please file under one of the global project boards with a priority.

**Comment by jliangTT** [comment]
want to confirm that this is p0_showstopper? it is not labeled but set to P0 locally for kernel-op board

**Comment by jliangTT** [comment]
ok. talk offline: i am setting. moving this to P1 critical as something is really wrong program cache (the current workaround for model owner is disabling it). We need to investigate to see if this is an infra problem, or an op. 

Since it is not clear at the moment, i will triage it to TTNN as a starting point to triage.

**Comment by jliangTT** [comment]
Per @arakhmati , the program cache is not supported on multi-device. Will switch this to a feature. And with the popular request from the LLM for this feature, will keep the priority at P1, @TT-BrianLiu will work with @arakhmati to bring up this feature. 

Keeping this in the tt-nn project board since it is infra related.

**Comment by jliangTT** [comment]
@TT-BrianLiu , said he is working on this. please confirm?

**Comment by jliangTT** [comment]
any update on this?

**Comment by TT-BrianLiu** [comment]
I created a multi-chip test for program cache to do some digging. It seems like currently we are caching something (not sure what) that has device hashed, so we are actually generating program caches for multi-chip. We should see what in our current hashing scheme is hashing the device (my guess is input tensors have knowledge of device??) and explicitly cache for multi-chip.

This means two things:
- If all the ops in current multi-chip graphs all do this multi-chip caching implicitly, that means whatever hangs/PCC issues we are seeing is not related to program caching. 
- If there are some ops (ex. some ops also override the default hashing function) that are not doing the multi-chip caching implicitly, then when we add proper caching for device, I would expect some of these issues to be fixed.

**Comment by davorchap** [comment]
> I created a multi-chip test for program cache to do some digging. It seems like currently we are caching something (not sure what) that has device hashed, so we are actually generating program caches for multi-chip. We should see what in our current hashing scheme is hashing the device (my guess is input tensors have knowledge of device??) and explicitly cache for multi-chip.
> 
> 
> 
> This means two things:
> 
> - If all the ops in current multi-chip graphs all do this multi-chip caching implicitly, that means whatever hangs/PCC issues we are seeing is not related to program caching. 
> 
> - If there are some ops (ex. some ops also override the default hashing function) that are not doing the multi-chip caching implicitly, then when we add proper caching for device, I would expect some of these issues to be fixed.

When @tt-aho was bringing up first multi device Falcon40 he included device_id into the hash for the program. Device id is probably from input tensors.

Let's sync with Austin on Monday. 
It may not be necessarily a cache issue. 
It could be that we have a race and disabling the cache just slows down dispatch and the race is bypassed.

Perhaps we can try cache plus sleep(1) between OPs and see if that also results in good PCC.

**Comment by TT-BrianLiu** [comment]
@tt-aho Did you add device to kernel or program hash as well? Right now, there doesn't seem to be anything explicit for the program cache

**Comment by tt-aho** [comment]
I think device id has been part of kernel path/hash for a long time now? There should be folders by id in built/kernels. Ex built/kernels/0

For program cache, device id was added to the hash of the tensor object, and tensors are hashed by default for program cache. If the op writer is manually overriding the op hash function they need to add device id manually to the hash. I should have updated all of the existing ops that were overriding hash function to do this.

**Comment by TT-BrianLiu** [comment]
We are switching program cache to store separate hashes per device. Device id will be removed from the device buffer attributes (so tensor hash will also not contain device id) and all the explicit compute_hash functions. This will help debug easier, since each op will have the same hash across devices. More importantly, it's needed for this: #6254.

**Comment by aliuTT** [comment]
The hangs we're consistently seeing with program cache enabled on remote chips, is due to bidirectional tunneller not observing the max cmd slots for tensix cores, therefore it can end up in a deadlock scenario where the issue path is trying to forward more cmds when the remote pull and push kernel is blocked trying to send cmds back through the completion path.

With fix bdc566044, I am able to run AllGather test with 8 chips program cache many times, no hangs. I also tried Falcon40B 60 layers with program cache on 8 chips, it's now passing consistently.

The bug can affect any remote chip test (e.g. device 4,5,6,7 on T3000), please try commit with any reported hangs.
