### ISSUE TITLE
Llama2 8-chip hang

### ISSUE THREAD

**Issue by cglagovich** [tenstorrent-metal/tt-metal#6150]
**Describe the bug**
Running Llama2 model tests leads to a non-deterministic hang. So far, the hang reproduces consistently with 8 or more layers.

**To Reproduce**
1. `git checkout model-team/llama2-tunneling` (branch rebased on main as of 3/6)
2. `pytest -svv models/demos/llama2_70b/tests/test_llama_model.py::test_LlamaModel_inference[BFLOAT16-DRAM-32-1-True-8-False-0.98-8]`

**Expected behavior**
After producing one or two tokens, the test will hang.

**Screenshots**
<img width="1708" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/20099419/d349aa63-b54a-4802-bc48-eaed6293aac7">

**Please complete the following environment information:**
- machine `sjc-snva-t3002`

**Additional context**
Ask for information on reproing. We may have to force the test to not load weights since weights are only on `sjc-snva-t3002`.

**Comment by aliuTT** [comment]
From a slack conversation, Colman was unable to repro the hang with two changes:
- input to update_cache is sharded instead of interleaved
- K cache is bf16 rather than bfp8

I tried out the following experiments for Falcon40B:
- K cache b16 update_cache is interleaved: pass, but slightly bad PCC on output (~0.91)
- K cache b16 update_cache is sharded: pass, but slightly bad PCC on output (~0.91)
- K cache bfp8 update_cache is sharded: pass
- K cache bfp8 update_cache is interleaved: pass

So it doesn't look like some systemic issue with the model configs. Maybe just isolated to Llama

**Comment by aliuTT** [comment]
Downgrading to P1 since there is workaround

**Comment by cglagovich** [comment]
Haven't been able to repro the hang even after reverting the above changes Allan mentioned. Closing
