### ISSUE TITLE
interleaved_to_sharded op PCC error with Row Major input tensor

### ISSUE THREAD

**Issue by yugaoTT** [tenstorrent-metal/tt-metal#6197]
there is a bug in interleaved_to_sharded, when input tensor is row major and stored in DRAM, and width is not divisible by 32.
I tested 32x40 tensor on a singel core, it caused pcc error. When storing tensor in L1, it has no error

branch: `yugao/gn_pcc_fix`
run: `pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_sharded.py`

**Comment by tt-aho** [comment]
I pushed a fix for this to branch `aho/fix-shard-page-alignment` so that interleaved <-> sharded ops are aligning the pages in memory, however this could be potentially corrupting memory if shards aren't allocated to handle padding/alignment.

@tarafdarTT we need to spec out and define how unaligned pages within a shard should be handled, so that other ops know what to expect/how to handle this

**Comment by tt-aho** [comment]
This is resolved on main now
