### ISSUE TITLE
Multichip hang when running in non-blocking mode

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent-metal/tt-metal#6404]
Continuation of #6363

If you run on `agrebenisan/issue-6363-with-stash`, you will observe the following
- R chip successfully completes first two programs and relays command with event back to ethernet bidir tunneller core
- Bidir tunneller never enters API which forwards this command back to L chip

On a t3000 machine, run the following 
```
TT_METAL_DPRINT_CHIPS=0,1,2,3,4,5,6,7 TT_METAL_DPRINT_ETH_CORES="(0,1),(0,9)"  TT_METAL_DPRINT_CORES=all TT_METAL_WATCHER=40 python -m pytest tests/tt_eager/python_api_testing/unit_testing/misc/test_all_gather.py -k "post_commit and looping and  200-mem_config1-input_dtype1-8-1-input_shape2-3-layout2"
```

**Comment by SeanNijjar** [comment]
Thanks for opening this up. Might be related: https://github.com/tenstorrent-metal/tt-metal/issues/6388. no solid evidence. Just making the association so I can try that one after this is fixed.

**Comment by aliuTT** [comment]
The hangs we're consistently seeing with program cache enabled on remote chips, is due to bidirectional tunneller not observing the max cmd slots for tensix cores, therefore it can end up in a deadlock scenario where the issue path is trying to forward more cmds when the remote pull and push kernel is blocked trying to send cmds back through the completion path.

With fix `bdc566044`, I am able to run the test here many times, no hangs. I also tried Falcon40B 60 layers with program cache on 8 chips, it's now passing consistently.

The bug can affect any remote chip test (e.g. device 4,5,6,7 on T3000), please try commit with any reported hangs.

**Comment by jliangTT** [comment]
Can this be closed?

**Comment by aliuTT** [comment]
yes
