### ISSUE TITLE
EnqueueProgram Functional: TTNN conv test hang

### ISSUE THREAD

**Issue by aliuTT** [tenstorrent-metal/tt-metal#7263]
`pytest "tests/ttnn/unit_tests/operations/test_conv2d.py::test_halo_reshard_conv[use_1d_systolic_array=False-batch_size=1-output_channels=128-input_channels=128-input_height=32-input_width=32-filter_height=3-filter_width=3-stride_h=1-stride_w=1-pad_h=1-pad_w=1-config_override={'act_reshard_num_cores_nhw': 1}]"`

Hangs in conv op

**Comment by tt-aho** [comment]
One hang was caused by corruption of ncrisc binary.
We currrently always write program binary data using pages padded to PROGRAM_PAGE_SIZE instead of true page size, but the dst addresses we write binaries to may be within this padded size, so we end up corrupting some parts of the binary. Workaround is to use a smaller program page size (ex. 256) to avoid this corruption until we support writing true page sizes and striding correctly in dispatcher.


Currently the conv op still hangs somewhere in the kernel execution, but we at least see all riscs have entered their kernel

**Comment by tt-aho** [comment]
Found the issue, we only provide 4 bits for the page_offset for read_pages, so when the page_offset for the program binaries with multiple spans is > 15, we need to pass in a base address that is offset to reduce the page_offset value we need to pass

**Comment by aliuTT** [comment]
Hmm how big was the total size? I think when we use larger page sizes, this wouldn't be an issue

**Comment by tt-aho** [comment]
I'd have to check but yes having a larger page size would mean our page_offset would be smaller.

Is there a maximum program binary size we support?

**Comment by aliuTT** [comment]
I think 4k is the max of the L1 we can write to. So maybe 4k/8 = 512 is probably the smallest page size with 4 bits as offset
